### ISSUE TITLE
Uploader is so close to working under Python 3

### ISSUE THREAD

**Issue by konklone** [jjjake/ia-wrapper#76]
I've been trying to get ~40GB of government reports into the Archive, as detailed in https://github.com/unitedstates/inspectors-general/issues/63. It's a Python 3 project, so I've been running up against some hurdles.

1. Annoying, but not a dealbreaker, is that I can't use the `[speedups]` tag in my `requirements.txt`, because `gevent` is not compatible with Python 3. I see you're working on a refactor to use asyncio, which I :+1:'d in https://github.com/jjjake/ia-wrapper/issues/75#issuecomment-61389113 and would be very helpful.
2. A bigger problem is that the uploader and request object do some unicode encoding/decoding stuff that doesn't exist in Python 3 (because all strings are unicode strings) and is depending on `__iter__` _not_ being defined on `str` (in Python 3, it is).

I resoved `2.` with a surgical but ugly hack, which you can see [in this branch compare](https://github.com/konklone/ia-wrapper/compare/py3-hack), and so now I'm working off of my fork for the time being.

To make the uploader work under Python 3 _and_ still work under Python 2 will require a bit more work than my hack, but it should be possible.

**Comment by jjjake** [comment]
Uploads should now work in py3, see e34f625c50ee0a652f42902eaa09958ea7def8ea

**Comment by konklone** [comment]
Thank you!!
